# Generated by Django 5.2.16 on 2026-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_backfill_normalized_playlist_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
